Add raw codeFrame and fix JSONError type
sindresorhus/parse-json pull request #37
Opened 2023-08-30 19:48 UTC by crondinini

### Description

Needed to get the code lines without the highlighting, so I have introduced a new property for it. 

Also fixes JSONError to be a class, the `instanceof` comparison can be used in a Typescript codebase.

2023-08-31 11:27 UTC, sindresorhus requested changes

2023-08-31 11:27 UTC, sindresorhus commented on test.js
> +		t.true(error.rawCodeFrame === '  1 | {\n  2 | \t"foo": true,\n> 3 | }\n    | ^');
Use `t.is()`

2023-08-31 11:27 UTC, sindresorhus commented
You need to add it to the readme and index.d.ts

2023-08-31 22:56 UTC, crondinini commented on test.js
> +		t.true(error.rawCodeFrame === '  1 | {\n  2 | \t"foo": true,\n> 3 | }\n    | ^');
Done

2023-09-01 06:37 UTC, merged

2023-09-01 14:24 UTC, sindresorhus commented
This was already merged and released.